# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/moso',
                'doc_host': 'https://dienhoa.github.io',
                'git_url': 'https://github.com/dienhoa/moso',
                'lib_path': 'moso'},
  'syms': { 'moso.core': { 'moso.core._get_moso_jupyter': ('core.html#_get_moso_jupyter', 'moso/core.py'),
                           'moso.core._get_moso_solveit': ('core.html#_get_moso_solveit', 'moso/core.py'),
                           'moso.core._run_moso': ('core.html#_run_moso', 'moso/core.py'),
                           'moso.core.filter_moso': ('core.html#filter_moso', 'moso/core.py'),
                           'moso.core.get_moso': ('core.html#get_moso', 'moso/core.py'),
                           'moso.core.setup_moso': ('core.html#setup_moso', 'moso/core.py')}}}
