"""Cumulative Mojo cell magic for SolveIt

Docs: https://dienhoa.github.io/mosocore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['filter_moso', 'get_moso', 'setup_moso']

# %% ../nbs/00_core.ipynb #b2320e55
import re, subprocess, sys
from pathlib import Path
from IPython.core.magic import register_cell_magic

# %% ../nbs/00_core.ipynb #9629696e
def filter_moso(msgs):
    "Strip %%moso magic lines and concatenate into one Mojo source"
    pat = re.compile(r"^%%moso[^\n]*\n", re.MULTILINE)
    bodies = [pat.sub("", m["content"], count=1) for m in msgs]
    if not bodies: return ""
    *preamble,last = bodies
    indented = "\n".join("    " + line for line in last.splitlines())
    return "\n".join(preamble + [f"def main() raises:\n{indented}"])

# %% ../nbs/00_core.ipynb #4405246b
async def get_moso():
    "Get concatenated Mojo source from all %%moso cells up to the current one"
    from dialoghelper import read_msg, find_msgs
    cur_id = (await read_msg(0))["id"]
    all_moso = await find_msgs(r"^%%moso", msg_type="code", include_output=False)
    upto = []
    for m in all_moso:
        upto.append(m)
        if m["id"] == cur_id: break
    return filter_moso(upto)

# %% ../nbs/00_core.ipynb #149130e0
def setup_moso(host=None, cmd="mojo run {path}", path="/tmp/cell.mojo"):
    "Register the %%moso magic"
    @register_cell_magic
    async def moso(line, cell):
        source = await get_moso()
        run_cmd = cmd.format(path=path)
        if host:
            full_cmd = f"ssh {host} 'cat > {path} && {run_cmd}'"
            result = subprocess.run(full_cmd, shell=True, input=source.encode(), capture_output=True)
        else:
            Path(path).write_text(source)
            result = subprocess.run(run_cmd, shell=True, capture_output=True)
        if result.returncode == 0:
            if result.stdout: print(result.stdout.decode())
        else: print(result.stderr.decode(), file=sys.stderr)
